### ISSUE TITLE
Unit Tests Failing with Source Compilation

### ISSUE THREAD

**Issue by zerokhash** [johnoliverdriscoll/py-ggmpc#3]
Running local compilation of the project, after installing the default source requirements:

Is it due to dependency/python versioning issues?

python3 -m unittest -v

test_2_in_2_of_3 (test.test_command_line.Ecdsa) ... ERROR
test_3_in_3_of_5 (test.test_command_line.Ecdsa) ... ERROR
test_2_in_2_of_3 (test.test_command_line.Eddsa) ... ok
test_3_in_3_of_5 (test.test_command_line.Eddsa) ... ok
test_secret (test.test_command_line.Eddsa) ... ok
test_2_in_2_of_3 (test.test_ecdsa.Ecdsa) ... ERROR
test_2_in_3_of_5 (test.test_ecdsa.Ecdsa) ... ERROR
test_3_in_3_of_5 (test.test_ecdsa.Ecdsa) ... ERROR
test_2_in_2_of_3 (test.test_eddsa.Eddsa) ... ok
test_2_in_3_of_5 (test.test_eddsa.Eddsa) ... ok
test_3_in_3_of_5 (test.test_eddsa.Eddsa) ... ok
test_offset (test.test_eddsa.Eddsa) ... ok

======================================================================
ERROR: test_2_in_2_of_3 (test.test_command_line.Ecdsa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zero/Downloads/py-ggmpc/test/test_command_line.py", line 44, in test_2_in_2_of_3
    BA = Ecdsa.ggmpc('signshare', B[0], A[1])
  File "/Users/zero/Downloads/py-ggmpc/test/test_command_line.py", line 22, in ggmpc
    raise RuntimeError(process.stderr.decode('ascii'))
RuntimeError: Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
ValueError: unsupported hash type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_maino
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/zero/Downloads/py-ggmpc/src/ggmpc/__main__.py", line 775, in <module>
    main()
  File "/Users/zero/Downloads/py-ggmpc/src/ggmpc/__main__.py", line 409, in main
    args.func(Ecdsa(getattr(curves, args.c)), args)
  File "/Users/zero/Downloads/py-ggmpc/src/ggmpc/__main__.py", line 453, in ecdsa_sign_share
    shares = mpc.sign_share(list(map(deserialize, args.CHALLENGE)))
  File "/Users/zero/Downloads/py-ggmpc/src/ggmpc/ecdsa.py", line 248, in sign_share
    z, u, w, s, s1, s2 = prove_range(self.curve, pka, ck, ntildeb, h1b, h2b, k, rk)
  File "/Users/zero/Downloads/py-ggmpc/src/ggmpc/ecdsa.py", line 725, in prove_range
    hash = hashlib.new('sha512_256')
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512_256

**Comment by zerokhash** [comment]
File "/Users/zero/Downloads/py-ggmpc/src/ggmpc/curves.py", line 111, in <lambda>
    lambda a, b: (a + b) % _secp256k1_order,
TypeError: can only concatenate str (not "int") to str

Replaced hashlib with hashlib.new('sha512_256'):
from Crypto.Hash import SHA512
hash = SHA512.new(truncate="256")
